/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import universidade.Controlador;

/**
 *
 * @author Pedro Henrique Zago Costa - R.A.: 181257084
 * 
 * BuscaDepartamentoPorCodigo.java -> Este JDialog é responsável por receber a
 * entrada que representa o código do Departamento a ser buscado.
 */
public class BuscaDepartamentoPorCodigo extends javax.swing.JDialog {

    /**
     * Creates new form BuscaDepartamentoPorCodigo
     */
    public BuscaDepartamentoPorCodigo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        BuscarDepartamentoPorCodigo_Buscar.setEnabled(false);
        this.setTitle("Exibir Informações de Departamento");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BuscarDepartamentoPorCodigo_Titulo = new javax.swing.JLabel();
        BuscarDepartamentoPorCodigo_Descricao = new javax.swing.JLabel();
        BuscarDepartamentoPorCodigo_Inserir_codigo = new javax.swing.JLabel();
        BuscarDepartamentoPorCodigo_codigo_in = new javax.swing.JTextField();
        BuscarDepartamentoPorCodigo_Buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        BuscarDepartamentoPorCodigo_Titulo.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        BuscarDepartamentoPorCodigo_Titulo.setText("Exibir Informações de Departamento");

        BuscarDepartamentoPorCodigo_Descricao.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        BuscarDepartamentoPorCodigo_Descricao.setForeground(new java.awt.Color(0, 0, 153));
        BuscarDepartamentoPorCodigo_Descricao.setText("Exibirá todas as informações de um departamento a partir de seu código (caso exista):");

        BuscarDepartamentoPorCodigo_Inserir_codigo.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        BuscarDepartamentoPorCodigo_Inserir_codigo.setText("Inserir código:");

        BuscarDepartamentoPorCodigo_codigo_in.setBackground(new java.awt.Color(204, 204, 255));
        BuscarDepartamentoPorCodigo_codigo_in.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BuscarDepartamentoPorCodigo_codigo_inKeyPressed(evt);
            }
        });

        BuscarDepartamentoPorCodigo_Buscar.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        BuscarDepartamentoPorCodigo_Buscar.setText("Buscar");
        BuscarDepartamentoPorCodigo_Buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarDepartamentoPorCodigo_BuscarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BuscarDepartamentoPorCodigo_Inserir_codigo)
                                .addGap(18, 18, 18)
                                .addComponent(BuscarDepartamentoPorCodigo_codigo_in, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BuscarDepartamentoPorCodigo_Descricao)
                            .addComponent(BuscarDepartamentoPorCodigo_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(BuscarDepartamentoPorCodigo_Buscar)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BuscarDepartamentoPorCodigo_Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BuscarDepartamentoPorCodigo_Descricao)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuscarDepartamentoPorCodigo_Inserir_codigo)
                    .addComponent(BuscarDepartamentoPorCodigo_codigo_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BuscarDepartamentoPorCodigo_Buscar)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarDepartamentoPorCodigo_BuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarDepartamentoPorCodigo_BuscarMouseClicked
        if (BuscarDepartamentoPorCodigo_Buscar.isEnabled()) {
            String codigo = BuscarDepartamentoPorCodigo_codigo_in.getText();
            Controlador control = new Controlador();
            Relatorio relatorio10 = new Relatorio(null, true);
            String aux = control.exibicaoDepartamentos(codigo);
            relatorio10.exibir(aux);
            dispose();
        }
    }//GEN-LAST:event_BuscarDepartamentoPorCodigo_BuscarMouseClicked

    private void BuscarDepartamentoPorCodigo_codigo_inKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscarDepartamentoPorCodigo_codigo_inKeyPressed
        if (!"".equals(BuscarDepartamentoPorCodigo_codigo_in.getText())) {
            BuscarDepartamentoPorCodigo_Buscar.setEnabled(true);
        }
    }//GEN-LAST:event_BuscarDepartamentoPorCodigo_codigo_inKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscaDepartamentoPorCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscaDepartamentoPorCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscaDepartamentoPorCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscaDepartamentoPorCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BuscaDepartamentoPorCodigo dialog = new BuscaDepartamentoPorCodigo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarDepartamentoPorCodigo_Buscar;
    private javax.swing.JLabel BuscarDepartamentoPorCodigo_Descricao;
    private javax.swing.JLabel BuscarDepartamentoPorCodigo_Inserir_codigo;
    private javax.swing.JLabel BuscarDepartamentoPorCodigo_Titulo;
    private javax.swing.JTextField BuscarDepartamentoPorCodigo_codigo_in;
    // End of variables declaration//GEN-END:variables
}
