/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import universidade.Controlador;

/**
 *
 * @author Pedro Henrique Zago Costa - R.A.: 181257084
 * 
 * BuscaFuncionarioPorCodigo.java -> Este JDialog é responsável por receber a
 * entrada que representa o código do Funcionário a ser buscado.
 */
public class BuscaFuncionarioPorCodigo extends javax.swing.JDialog {

    /**
     * Creates new form BuscaFuncionarioPorCodigo
     */
    public BuscaFuncionarioPorCodigo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        BuscarFuncionarioPorCodigo_Buscar.setEnabled(false);
        this.setTitle("Busca de Funcionários por Código");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BuscarFuncionarioPorCodigo_Titulo = new javax.swing.JLabel();
        BuscarFuncionarioPorCodigo_Descricao = new javax.swing.JLabel();
        BuscarFuncionarioPorCodigo_Inserir_codigo = new javax.swing.JLabel();
        BuscarFuncionarioPorCodigo_codigo_in = new javax.swing.JTextField();
        BuscarFuncionarioPorCodigo_Buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        BuscarFuncionarioPorCodigo_Titulo.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        BuscarFuncionarioPorCodigo_Titulo.setText("Busca de Funcionário por Código");

        BuscarFuncionarioPorCodigo_Descricao.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        BuscarFuncionarioPorCodigo_Descricao.setForeground(new java.awt.Color(0, 0, 153));
        BuscarFuncionarioPorCodigo_Descricao.setText("Exibirá os dados de um funcionário a partir de seu código (caso exista):");

        BuscarFuncionarioPorCodigo_Inserir_codigo.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        BuscarFuncionarioPorCodigo_Inserir_codigo.setText("Inserir código:");

        BuscarFuncionarioPorCodigo_codigo_in.setBackground(new java.awt.Color(204, 204, 255));
        BuscarFuncionarioPorCodigo_codigo_in.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BuscarFuncionarioPorCodigo_codigo_inKeyPressed(evt);
            }
        });

        BuscarFuncionarioPorCodigo_Buscar.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        BuscarFuncionarioPorCodigo_Buscar.setText("Buscar");
        BuscarFuncionarioPorCodigo_Buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarFuncionarioPorCodigo_BuscarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BuscarFuncionarioPorCodigo_Inserir_codigo)
                                .addGap(18, 18, 18)
                                .addComponent(BuscarFuncionarioPorCodigo_codigo_in, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BuscarFuncionarioPorCodigo_Descricao)
                            .addComponent(BuscarFuncionarioPorCodigo_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(BuscarFuncionarioPorCodigo_Buscar)))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BuscarFuncionarioPorCodigo_Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BuscarFuncionarioPorCodigo_Descricao)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuscarFuncionarioPorCodigo_Inserir_codigo)
                    .addComponent(BuscarFuncionarioPorCodigo_codigo_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BuscarFuncionarioPorCodigo_Buscar)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarFuncionarioPorCodigo_BuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarFuncionarioPorCodigo_BuscarMouseClicked
        if (BuscarFuncionarioPorCodigo_Buscar.isEnabled()) {
            String codigo = BuscarFuncionarioPorCodigo_codigo_in.getText();
            Controlador control = new Controlador();
            Relatorio relatorio11 = new Relatorio(null, true);
            String aux = control.buscaFuncionarios(1, codigo);
            relatorio11.exibir(aux);
            dispose();
        }
    }//GEN-LAST:event_BuscarFuncionarioPorCodigo_BuscarMouseClicked

    private void BuscarFuncionarioPorCodigo_codigo_inKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscarFuncionarioPorCodigo_codigo_inKeyPressed
        if (!"".equals(BuscarFuncionarioPorCodigo_codigo_in.getText())) {
            BuscarFuncionarioPorCodigo_Buscar.setEnabled(true);
        }
    }//GEN-LAST:event_BuscarFuncionarioPorCodigo_codigo_inKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscaFuncionarioPorCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscaFuncionarioPorCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscaFuncionarioPorCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscaFuncionarioPorCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BuscaFuncionarioPorCodigo dialog = new BuscaFuncionarioPorCodigo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarFuncionarioPorCodigo_Buscar;
    private javax.swing.JLabel BuscarFuncionarioPorCodigo_Descricao;
    private javax.swing.JLabel BuscarFuncionarioPorCodigo_Inserir_codigo;
    private javax.swing.JLabel BuscarFuncionarioPorCodigo_Titulo;
    private javax.swing.JTextField BuscarFuncionarioPorCodigo_codigo_in;
    // End of variables declaration//GEN-END:variables
}
