/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
        
import universidade.Sistema;
import universidade.Controlador;

/**
 *
 * @author Pedro Henrique Zago Costa - R.A.: 181257084
 * 
 * MenuPrincipal.java -> este JFrame é o menu principal deste programa. A partir
 * dele, todas as outras janelas são chamadas.
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.setTitle("Menu Principal");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuPrincipal_Titulo = new javax.swing.JLabel();
        MenuPrincipal_Inserir_Funcionario = new javax.swing.JLabel();
        MenuPrincipal_Inserir_Departamento = new javax.swing.JLabel();
        MenuPrincipal_Novo_Departamento = new javax.swing.JButton();
        MenuPrincipal_Novo_Tecnico = new javax.swing.JButton();
        MenuPrincipal_Novo_Docente_Efetivo = new javax.swing.JButton();
        MenuPrincipal_Novo_Docente_Substituto = new javax.swing.JButton();
        MenuPrincipal_Exibicao_Geral = new javax.swing.JLabel();
        MenuPrincipal_Geral_Exibir = new javax.swing.JButton();
        MenuPrincipal_Departamentos = new javax.swing.JLabel();
        MenuPrincipal_Resumo_Geral = new javax.swing.JButton();
        MenuPrincipal_Com_Faixa_de_gastos_Especifica = new javax.swing.JButton();
        MenuPrincipal_Funcionarios_com_Salario_Especifico = new javax.swing.JLabel();
        MenuPrincipal_Buscar = new javax.swing.JButton();
        MenuPrincipal_Exibicao_de_Funcionarios = new javax.swing.JLabel();
        MenuPrincipal_Todos_os_Funcionarios = new javax.swing.JButton();
        MenuPrincipal_Todos_os_Tecnicos = new javax.swing.JButton();
        MenuPrincial_Todos_os_Docentes = new javax.swing.JButton();
        MenuPrincipal_Todos_os_Docentes_Efetivos = new javax.swing.JButton();
        MenuPrincipal_Todos_os_Docentes_Substitutos = new javax.swing.JButton();
        MenuPrincipal_Exibicao_de_Departamentos = new javax.swing.JLabel();
        MenuPrincipal_Departamentos_Exibir = new javax.swing.JButton();
        MenuPrincipal_Busca_de_Funcionario = new javax.swing.JLabel();
        MenuPrincipal_Por_codigo = new javax.swing.JButton();
        MenuPrincipal_Por_nome = new javax.swing.JButton();
        MenuPrincipal_Fechar_o_Sistema = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        MenuPrincipal_Titulo.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        MenuPrincipal_Titulo.setText("Menu Principal");

        MenuPrincipal_Inserir_Funcionario.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        MenuPrincipal_Inserir_Funcionario.setForeground(new java.awt.Color(153, 0, 0));
        MenuPrincipal_Inserir_Funcionario.setText("Inserir Funcionário:");

        MenuPrincipal_Inserir_Departamento.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        MenuPrincipal_Inserir_Departamento.setForeground(new java.awt.Color(153, 0, 0));
        MenuPrincipal_Inserir_Departamento.setText("Inserir Departamento:");

        MenuPrincipal_Novo_Departamento.setBackground(new java.awt.Color(255, 204, 204));
        MenuPrincipal_Novo_Departamento.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        MenuPrincipal_Novo_Departamento.setForeground(new java.awt.Color(153, 0, 0));
        MenuPrincipal_Novo_Departamento.setText("Novo Departamento");
        MenuPrincipal_Novo_Departamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuPrincipal_Novo_DepartamentoMouseClicked(evt);
            }
        });

        MenuPrincipal_Novo_Tecnico.setBackground(new java.awt.Color(255, 204, 204));
        MenuPrincipal_Novo_Tecnico.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        MenuPrincipal_Novo_Tecnico.setForeground(new java.awt.Color(153, 0, 0));
        MenuPrincipal_Novo_Tecnico.setText("Novo Técnico");
        MenuPrincipal_Novo_Tecnico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuPrincipal_Novo_TecnicoMouseClicked(evt);
            }
        });

        MenuPrincipal_Novo_Docente_Efetivo.setBackground(new java.awt.Color(255, 204, 204));
        MenuPrincipal_Novo_Docente_Efetivo.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        MenuPrincipal_Novo_Docente_Efetivo.setForeground(new java.awt.Color(153, 0, 0));
        MenuPrincipal_Novo_Docente_Efetivo.setText("Novo Docente Efetivo");
        MenuPrincipal_Novo_Docente_Efetivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuPrincipal_Novo_Docente_EfetivoMouseClicked(evt);
            }
        });

        MenuPrincipal_Novo_Docente_Substituto.setBackground(new java.awt.Color(255, 204, 204));
        MenuPrincipal_Novo_Docente_Substituto.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        MenuPrincipal_Novo_Docente_Substituto.setForeground(new java.awt.Color(153, 0, 0));
        MenuPrincipal_Novo_Docente_Substituto.setText("Novo Docente Substituto");
        MenuPrincipal_Novo_Docente_Substituto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuPrincipal_Novo_Docente_SubstitutoMouseClicked(evt);
            }
        });

        MenuPrincipal_Exibicao_Geral.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        MenuPrincipal_Exibicao_Geral.setForeground(new java.awt.Color(204, 153, 0));
        MenuPrincipal_Exibicao_Geral.setText("Exibição Geral:");

        MenuPrincipal_Geral_Exibir.setBackground(new java.awt.Color(255, 255, 204));
        MenuPrincipal_Geral_Exibir.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        MenuPrincipal_Geral_Exibir.setForeground(new java.awt.Color(204, 153, 0));
        MenuPrincipal_Geral_Exibir.setText("Exibir");
        MenuPrincipal_Geral_Exibir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuPrincipal_Geral_ExibirMouseClicked(evt);
            }
        });

        MenuPrincipal_Departamentos.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        MenuPrincipal_Departamentos.setForeground(new java.awt.Color(204, 153, 0));
        MenuPrincipal_Departamentos.setText("Departamentos:");

        MenuPrincipal_Resumo_Geral.setBackground(new java.awt.Color(255, 255, 204));
        MenuPrincipal_Resumo_Geral.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        MenuPrincipal_Resumo_Geral.setForeground(new java.awt.Color(204, 153, 0));
        MenuPrincipal_Resumo_Geral.setText("Resumo Geral");
        MenuPrincipal_Resumo_Geral.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MenuPrincipal_Resumo_Geral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuPrincipal_Resumo_GeralMouseClicked(evt);
            }
        });

        MenuPrincipal_Com_Faixa_de_gastos_Especifica.setBackground(new java.awt.Color(255, 255, 204));
        MenuPrincipal_Com_Faixa_de_gastos_Especifica.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        MenuPrincipal_Com_Faixa_de_gastos_Especifica.setForeground(new java.awt.Color(204, 153, 0));
        MenuPrincipal_Com_Faixa_de_gastos_Especifica.setText("Com Faixa de gastos Específica");
        MenuPrincipal_Com_Faixa_de_gastos_Especifica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuPrincipal_Com_Faixa_de_gastos_EspecificaMouseClicked(evt);
            }
        });

        MenuPrincipal_Funcionarios_com_Salario_Especifico.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        MenuPrincipal_Funcionarios_com_Salario_Especifico.setForeground(new java.awt.Color(204, 153, 0));
        MenuPrincipal_Funcionarios_com_Salario_Especifico.setText("Funcionários com Salário Específico:");

        MenuPrincipal_Buscar.setBackground(new java.awt.Color(255, 255, 204));
        MenuPrincipal_Buscar.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        MenuPrincipal_Buscar.setForeground(new java.awt.Color(204, 153, 0));
        MenuPrincipal_Buscar.setText("Buscar");
        MenuPrincipal_Buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuPrincipal_BuscarMouseClicked(evt);
            }
        });

        MenuPrincipal_Exibicao_de_Funcionarios.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        MenuPrincipal_Exibicao_de_Funcionarios.setForeground(new java.awt.Color(0, 0, 153));
        MenuPrincipal_Exibicao_de_Funcionarios.setText("Exibição de Funcionários:");

        MenuPrincipal_Todos_os_Funcionarios.setBackground(new java.awt.Color(204, 204, 255));
        MenuPrincipal_Todos_os_Funcionarios.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        MenuPrincipal_Todos_os_Funcionarios.setForeground(new java.awt.Color(0, 0, 153));
        MenuPrincipal_Todos_os_Funcionarios.setText("Todos os Funcionários");
        MenuPrincipal_Todos_os_Funcionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuPrincipal_Todos_os_FuncionariosMouseClicked(evt);
            }
        });

        MenuPrincipal_Todos_os_Tecnicos.setBackground(new java.awt.Color(204, 204, 255));
        MenuPrincipal_Todos_os_Tecnicos.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        MenuPrincipal_Todos_os_Tecnicos.setForeground(new java.awt.Color(0, 0, 153));
        MenuPrincipal_Todos_os_Tecnicos.setText("Todos os Técnicos");
        MenuPrincipal_Todos_os_Tecnicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuPrincipal_Todos_os_TecnicosMouseClicked(evt);
            }
        });

        MenuPrincial_Todos_os_Docentes.setBackground(new java.awt.Color(204, 204, 255));
        MenuPrincial_Todos_os_Docentes.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        MenuPrincial_Todos_os_Docentes.setForeground(new java.awt.Color(0, 0, 153));
        MenuPrincial_Todos_os_Docentes.setText("Todos os Docentes");
        MenuPrincial_Todos_os_Docentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuPrincial_Todos_os_DocentesMouseClicked(evt);
            }
        });

        MenuPrincipal_Todos_os_Docentes_Efetivos.setBackground(new java.awt.Color(204, 204, 255));
        MenuPrincipal_Todos_os_Docentes_Efetivos.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        MenuPrincipal_Todos_os_Docentes_Efetivos.setForeground(new java.awt.Color(0, 0, 153));
        MenuPrincipal_Todos_os_Docentes_Efetivos.setText("Todos os Docentes Efetivos");
        MenuPrincipal_Todos_os_Docentes_Efetivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuPrincipal_Todos_os_Docentes_EfetivosMouseClicked(evt);
            }
        });

        MenuPrincipal_Todos_os_Docentes_Substitutos.setBackground(new java.awt.Color(204, 204, 255));
        MenuPrincipal_Todos_os_Docentes_Substitutos.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        MenuPrincipal_Todos_os_Docentes_Substitutos.setForeground(new java.awt.Color(0, 0, 153));
        MenuPrincipal_Todos_os_Docentes_Substitutos.setText("Todos os Docentes Substitutos");
        MenuPrincipal_Todos_os_Docentes_Substitutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuPrincipal_Todos_os_Docentes_SubstitutosMouseClicked(evt);
            }
        });

        MenuPrincipal_Exibicao_de_Departamentos.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        MenuPrincipal_Exibicao_de_Departamentos.setForeground(new java.awt.Color(0, 0, 153));
        MenuPrincipal_Exibicao_de_Departamentos.setText("Exibição de Departamentos:");

        MenuPrincipal_Departamentos_Exibir.setBackground(new java.awt.Color(204, 204, 255));
        MenuPrincipal_Departamentos_Exibir.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        MenuPrincipal_Departamentos_Exibir.setForeground(new java.awt.Color(0, 0, 153));
        MenuPrincipal_Departamentos_Exibir.setText("Exibir");
        MenuPrincipal_Departamentos_Exibir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuPrincipal_Departamentos_ExibirMouseClicked(evt);
            }
        });

        MenuPrincipal_Busca_de_Funcionario.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        MenuPrincipal_Busca_de_Funcionario.setForeground(new java.awt.Color(0, 0, 153));
        MenuPrincipal_Busca_de_Funcionario.setText("Busca de Funcionário:");

        MenuPrincipal_Por_codigo.setBackground(new java.awt.Color(204, 204, 255));
        MenuPrincipal_Por_codigo.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        MenuPrincipal_Por_codigo.setForeground(new java.awt.Color(0, 0, 153));
        MenuPrincipal_Por_codigo.setText("Por código");
        MenuPrincipal_Por_codigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuPrincipal_Por_codigoMouseClicked(evt);
            }
        });

        MenuPrincipal_Por_nome.setBackground(new java.awt.Color(204, 204, 255));
        MenuPrincipal_Por_nome.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        MenuPrincipal_Por_nome.setForeground(new java.awt.Color(0, 0, 153));
        MenuPrincipal_Por_nome.setText("Por nome");
        MenuPrincipal_Por_nome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuPrincipal_Por_nomeMouseClicked(evt);
            }
        });

        MenuPrincipal_Fechar_o_Sistema.setBackground(new java.awt.Color(255, 204, 204));
        MenuPrincipal_Fechar_o_Sistema.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        MenuPrincipal_Fechar_o_Sistema.setForeground(new java.awt.Color(204, 0, 0));
        MenuPrincipal_Fechar_o_Sistema.setText("Fechar o Sistema");
        MenuPrincipal_Fechar_o_Sistema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuPrincipal_Fechar_o_SistemaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(MenuPrincipal_Todos_os_Docentes_Substitutos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(MenuPrincipal_Todos_os_Docentes_Efetivos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MenuPrincial_Todos_os_Docentes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MenuPrincipal_Novo_Departamento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(MenuPrincipal_Inserir_Departamento))
                            .addComponent(MenuPrincipal_Geral_Exibir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MenuPrincipal_Exibicao_Geral, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54))
                            .addComponent(MenuPrincipal_Todos_os_Tecnicos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(MenuPrincipal_Exibicao_de_Funcionarios)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(MenuPrincipal_Com_Faixa_de_gastos_Especifica)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(MenuPrincipal_Exibicao_de_Departamentos)
                                                .addGap(67, 67, 67)
                                                .addComponent(MenuPrincipal_Busca_de_Funcionario))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(MenuPrincipal_Novo_Docente_Substituto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                                .addComponent(MenuPrincipal_Novo_Docente_Efetivo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(MenuPrincipal_Novo_Tecnico, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(MenuPrincipal_Fechar_o_Sistema))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(MenuPrincipal_Resumo_Geral, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(53, 53, 53)
                                                        .addComponent(MenuPrincipal_Departamentos)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(MenuPrincipal_Funcionarios_com_Salario_Especifico)
                                                    .addComponent(MenuPrincipal_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(30, 30, 30))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(MenuPrincipal_Inserir_Funcionario))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(217, 217, 217)
                                        .addComponent(MenuPrincipal_Por_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MenuPrincipal_Titulo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MenuPrincipal_Todos_os_Funcionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MenuPrincipal_Departamentos_Exibir, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MenuPrincipal_Por_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MenuPrincipal_Titulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MenuPrincipal_Inserir_Departamento)
                    .addComponent(MenuPrincipal_Inserir_Funcionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MenuPrincipal_Novo_Departamento)
                    .addComponent(MenuPrincipal_Novo_Tecnico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuPrincipal_Novo_Docente_Efetivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MenuPrincipal_Novo_Docente_Substituto)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MenuPrincipal_Exibicao_Geral)
                    .addComponent(MenuPrincipal_Departamentos)
                    .addComponent(MenuPrincipal_Funcionarios_com_Salario_Especifico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MenuPrincipal_Geral_Exibir)
                    .addComponent(MenuPrincipal_Resumo_Geral)
                    .addComponent(MenuPrincipal_Buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuPrincipal_Com_Faixa_de_gastos_Especifica)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MenuPrincipal_Exibicao_de_Funcionarios)
                    .addComponent(MenuPrincipal_Exibicao_de_Departamentos)
                    .addComponent(MenuPrincipal_Busca_de_Funcionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MenuPrincipal_Todos_os_Funcionarios)
                    .addComponent(MenuPrincipal_Departamentos_Exibir)
                    .addComponent(MenuPrincipal_Por_codigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MenuPrincipal_Por_nome)
                    .addComponent(MenuPrincipal_Todos_os_Tecnicos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuPrincial_Todos_os_Docentes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuPrincipal_Todos_os_Docentes_Efetivos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuPrincipal_Todos_os_Docentes_Substitutos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuPrincipal_Fechar_o_Sistema)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuPrincipal_Novo_DepartamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPrincipal_Novo_DepartamentoMouseClicked
        Sistema s1 = Sistema.getInstance();
        if (s1.maxDepart == 9) {new Mensagem04(null, true).setVisible(true);}
        else {new NovoDepartamento(null, true).setVisible(true);}
    }//GEN-LAST:event_MenuPrincipal_Novo_DepartamentoMouseClicked

    private void MenuPrincipal_Novo_TecnicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPrincipal_Novo_TecnicoMouseClicked
        Sistema s2 = Sistema.getInstance();
        if (s2.maxDepart == 0) {new Mensagem00(null, true).setVisible(true);}
        else if (s2.maxFunc == 99) {new Mensagem03(null, true).setVisible(true);}
        else {new NovoTecnico(null, true).setVisible(true);}
    }//GEN-LAST:event_MenuPrincipal_Novo_TecnicoMouseClicked

    private void MenuPrincipal_Novo_Docente_EfetivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPrincipal_Novo_Docente_EfetivoMouseClicked
        Sistema s3 = Sistema.getInstance();
        if (s3.maxDepart == 0) {new Mensagem00(null, true).setVisible(true);}
        else if (s3.maxFunc == 99) {new Mensagem03(null, true).setVisible(true);}
        else {new NovoEfetivo(null, true).setVisible(true);}
    }//GEN-LAST:event_MenuPrincipal_Novo_Docente_EfetivoMouseClicked

    private void MenuPrincipal_Novo_Docente_SubstitutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPrincipal_Novo_Docente_SubstitutoMouseClicked
        Sistema s4 = Sistema.getInstance();
        if (s4.maxDepart == 0) {new Mensagem00(null, true).setVisible(true);}
        else if (s4.maxFunc == 99) {new Mensagem03(null, true).setVisible(true);}
        else {new NovoSubstituto(null, true).setVisible(true);}
    }//GEN-LAST:event_MenuPrincipal_Novo_Docente_SubstitutoMouseClicked

    private void MenuPrincipal_Geral_ExibirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPrincipal_Geral_ExibirMouseClicked
        Sistema s5 = Sistema.getInstance();
        if (s5.maxDepart == 0) {new Mensagem02(null, true).setVisible(true);}
        else {
            Controlador control = new Controlador();
            Relatorio relatorio1 = new Relatorio(this, true);
            String aux = control.exibicaoGeral();
            relatorio1.exibir(aux);
        }
    }//GEN-LAST:event_MenuPrincipal_Geral_ExibirMouseClicked

    private void MenuPrincipal_Resumo_GeralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPrincipal_Resumo_GeralMouseClicked
        Sistema s6 = Sistema.getInstance();
        if (s6.maxDepart == 0) {new Mensagem02(null, true).setVisible(true);}
        else {
            Controlador control = new Controlador();
            Relatorio relatorio2 = new Relatorio(this, true);
            String aux = control.resumoDepartamentos(1, 0, 0);
            relatorio2.exibir(aux);
        }
    }//GEN-LAST:event_MenuPrincipal_Resumo_GeralMouseClicked

    private void MenuPrincipal_Com_Faixa_de_gastos_EspecificaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPrincipal_Com_Faixa_de_gastos_EspecificaMouseClicked
        Sistema s7 = Sistema.getInstance();
        if (s7.maxDepart == 0) {new Mensagem02(null, true).setVisible(true);}
        else {new DepartamentosFaixaEspecifica(null, true).setVisible(true);}
    }//GEN-LAST:event_MenuPrincipal_Com_Faixa_de_gastos_EspecificaMouseClicked

    private void MenuPrincipal_BuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPrincipal_BuscarMouseClicked
        Sistema s8 = Sistema.getInstance();
        if (s8.maxFunc == 0) {new Mensagem01(null, true).setVisible(true);}
        else {new FuncionariosSalarioEspecifico(null, true).setVisible(true);}
    }//GEN-LAST:event_MenuPrincipal_BuscarMouseClicked

    private void MenuPrincipal_Todos_os_FuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPrincipal_Todos_os_FuncionariosMouseClicked
        Sistema s9 = Sistema.getInstance();
        if (s9.maxFunc == 0) {new Mensagem01(null, true).setVisible(true);}
        else {
            Controlador control = new Controlador();
            Relatorio relatorio5 = new Relatorio(this, true);
            String aux = control.exibicaoFuncionarios(1);
            relatorio5.exibir(aux);
        }
    }//GEN-LAST:event_MenuPrincipal_Todos_os_FuncionariosMouseClicked

    private void MenuPrincipal_Todos_os_TecnicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPrincipal_Todos_os_TecnicosMouseClicked
        Sistema s10 = Sistema.getInstance();
        if (s10.maxFunc == 0) {new Mensagem01(null, true).setVisible(true);}
        else {
            Controlador control = new Controlador();
            Relatorio relatorio6 = new Relatorio(this, true);
            String aux = control.exibicaoFuncionarios(2);
            relatorio6.exibir(aux);
        }
    }//GEN-LAST:event_MenuPrincipal_Todos_os_TecnicosMouseClicked

    private void MenuPrincial_Todos_os_DocentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPrincial_Todos_os_DocentesMouseClicked
        Sistema s11 = Sistema.getInstance();
        if (s11.maxFunc == 0) {new Mensagem01(null, true).setVisible(true);}
        else {
            Controlador control = new Controlador();
            Relatorio relatorio7 = new Relatorio(this, true);
            String aux = control.exibicaoFuncionarios(3);
            relatorio7.exibir(aux);
        }
    }//GEN-LAST:event_MenuPrincial_Todos_os_DocentesMouseClicked

    private void MenuPrincipal_Todos_os_Docentes_EfetivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPrincipal_Todos_os_Docentes_EfetivosMouseClicked
        Sistema s12 = Sistema.getInstance();
        if (s12.maxFunc == 0) {new Mensagem01(null, true).setVisible(true);}
        else {
            Controlador control = new Controlador();
            Relatorio relatorio8 = new Relatorio(this, true);
            String aux = control.exibicaoFuncionarios(4);
            relatorio8.exibir(aux);
        }
    }//GEN-LAST:event_MenuPrincipal_Todos_os_Docentes_EfetivosMouseClicked

    private void MenuPrincipal_Todos_os_Docentes_SubstitutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPrincipal_Todos_os_Docentes_SubstitutosMouseClicked
        Sistema s13 = Sistema.getInstance();
        if (s13.maxFunc == 0) {new Mensagem01(null, true).setVisible(true);}
        else {
            Controlador control = new Controlador();
            Relatorio relatorio9 = new Relatorio(this, true);
            String aux = control.exibicaoFuncionarios(5);
            relatorio9.exibir(aux);
        }
    }//GEN-LAST:event_MenuPrincipal_Todos_os_Docentes_SubstitutosMouseClicked

    private void MenuPrincipal_Departamentos_ExibirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPrincipal_Departamentos_ExibirMouseClicked
        Sistema s14 = Sistema.getInstance();
        if (s14.maxDepart == 0) {new Mensagem02(null, true).setVisible(true);}
        else {new BuscaDepartamentoPorCodigo(null, true).setVisible(true);}
    }//GEN-LAST:event_MenuPrincipal_Departamentos_ExibirMouseClicked

    private void MenuPrincipal_Por_codigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPrincipal_Por_codigoMouseClicked
        Sistema s15 = Sistema.getInstance();
        if (s15.maxFunc == 0) {new Mensagem01(null, true).setVisible(true);}
        else {new BuscaFuncionarioPorCodigo(null, true).setVisible(true);}
    }//GEN-LAST:event_MenuPrincipal_Por_codigoMouseClicked

    private void MenuPrincipal_Por_nomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPrincipal_Por_nomeMouseClicked
        Sistema s16 = Sistema.getInstance();
        if (s16.maxFunc == 0) {new Mensagem01(null, true).setVisible(true);}
        else {new BuscaFuncionarioPorNome(null, true).setVisible(true);}
    }//GEN-LAST:event_MenuPrincipal_Por_nomeMouseClicked

    private void MenuPrincipal_Fechar_o_SistemaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPrincipal_Fechar_o_SistemaMouseClicked
        new Mensagem17(null, true).setVisible(true);
        dispose();
    }//GEN-LAST:event_MenuPrincipal_Fechar_o_SistemaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MenuPrincial_Todos_os_Docentes;
    private javax.swing.JLabel MenuPrincipal_Busca_de_Funcionario;
    private javax.swing.JButton MenuPrincipal_Buscar;
    private javax.swing.JButton MenuPrincipal_Com_Faixa_de_gastos_Especifica;
    private javax.swing.JLabel MenuPrincipal_Departamentos;
    private javax.swing.JButton MenuPrincipal_Departamentos_Exibir;
    private javax.swing.JLabel MenuPrincipal_Exibicao_Geral;
    private javax.swing.JLabel MenuPrincipal_Exibicao_de_Departamentos;
    private javax.swing.JLabel MenuPrincipal_Exibicao_de_Funcionarios;
    private javax.swing.JButton MenuPrincipal_Fechar_o_Sistema;
    private javax.swing.JLabel MenuPrincipal_Funcionarios_com_Salario_Especifico;
    private javax.swing.JButton MenuPrincipal_Geral_Exibir;
    private javax.swing.JLabel MenuPrincipal_Inserir_Departamento;
    private javax.swing.JLabel MenuPrincipal_Inserir_Funcionario;
    private javax.swing.JButton MenuPrincipal_Novo_Departamento;
    private javax.swing.JButton MenuPrincipal_Novo_Docente_Efetivo;
    private javax.swing.JButton MenuPrincipal_Novo_Docente_Substituto;
    private javax.swing.JButton MenuPrincipal_Novo_Tecnico;
    private javax.swing.JButton MenuPrincipal_Por_codigo;
    private javax.swing.JButton MenuPrincipal_Por_nome;
    private javax.swing.JButton MenuPrincipal_Resumo_Geral;
    private javax.swing.JLabel MenuPrincipal_Titulo;
    private javax.swing.JButton MenuPrincipal_Todos_os_Docentes_Efetivos;
    private javax.swing.JButton MenuPrincipal_Todos_os_Docentes_Substitutos;
    private javax.swing.JButton MenuPrincipal_Todos_os_Funcionarios;
    private javax.swing.JButton MenuPrincipal_Todos_os_Tecnicos;
    // End of variables declaration//GEN-END:variables
}
