/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import universidade.Sistema;
import universidade.Controlador;

/**
 *
 * @author Pedro Henrique Zago Costa - R.A.: 181257084
 * 
 * NovoEfetivo.java -> Este JDialog é responsável pelas entradas de dados
 * que representam as informações de um novo Docente Efetivo a ser cadastrado.
 */
public class NovoEfetivo extends javax.swing.JDialog {

    /**
     * Creates new form NovoEfetivo
     */
    public NovoEfetivo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        NovoEfetivo_Criar.setEnabled(false);
        setTitle("Novo Efetivo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NovoEfetivo_Titulo = new javax.swing.JLabel();
        NovoEfetivo_Descricao = new javax.swing.JLabel();
        NovoEfetivo_Inserir_codigo = new javax.swing.JLabel();
        NovoEfetivo_Inserir_nome = new javax.swing.JLabel();
        NovoEfetivo_Inserir_salario = new javax.swing.JLabel();
        NovoEfetivo_Inserir_nivel = new javax.swing.JLabel();
        NovoEfetivo_Inserir_titulacao = new javax.swing.JLabel();
        NovoEfetivo_Inserir_area = new javax.swing.JLabel();
        NovoEfetivo_codigo_in = new javax.swing.JTextField();
        NovoEfetivo_nome_in = new javax.swing.JTextField();
        NovoEfetivo_salario_in = new javax.swing.JTextField();
        NovoEfetivo_departamento_in = new javax.swing.JTextField();
        NovoEfetivo_nivel_in = new javax.swing.JComboBox<>();
        NovoEfetivo_titulacao_in = new javax.swing.JComboBox<>();
        NovoEfetivo_Criar = new javax.swing.JButton();
        NovoEfetivo_area_in = new javax.swing.JComboBox<>();
        NovoEfetivo_Inserir_departamento = new javax.swing.JLabel();
        NovoEfetivo_Aviso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        NovoEfetivo_Titulo.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        NovoEfetivo_Titulo.setText("Novo Docente Efetivo");

        NovoEfetivo_Descricao.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        NovoEfetivo_Descricao.setForeground(new java.awt.Color(153, 0, 0));
        NovoEfetivo_Descricao.setText("Inserir novo Docente Efetivo no Sistema:");

        NovoEfetivo_Inserir_codigo.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        NovoEfetivo_Inserir_codigo.setText("Inserir o código do Efetivo:");

        NovoEfetivo_Inserir_nome.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        NovoEfetivo_Inserir_nome.setText("Inserir o nome do Efetivo:");

        NovoEfetivo_Inserir_salario.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        NovoEfetivo_Inserir_salario.setText("Inserir o salário do Efetivo:");

        NovoEfetivo_Inserir_nivel.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        NovoEfetivo_Inserir_nivel.setText("Inserir o nível do Efetivo:");

        NovoEfetivo_Inserir_titulacao.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        NovoEfetivo_Inserir_titulacao.setText("Inserir a titulação do Efetivo:");

        NovoEfetivo_Inserir_area.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        NovoEfetivo_Inserir_area.setText("Inserir a área do Efetivo:");

        NovoEfetivo_codigo_in.setBackground(new java.awt.Color(255, 204, 204));
        NovoEfetivo_codigo_in.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NovoEfetivo_codigo_inKeyPressed(evt);
            }
        });

        NovoEfetivo_nome_in.setBackground(new java.awt.Color(255, 204, 204));
        NovoEfetivo_nome_in.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NovoEfetivo_nome_inKeyPressed(evt);
            }
        });

        NovoEfetivo_salario_in.setBackground(new java.awt.Color(255, 204, 204));
        NovoEfetivo_salario_in.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NovoEfetivo_salario_inKeyPressed(evt);
            }
        });

        NovoEfetivo_departamento_in.setBackground(new java.awt.Color(255, 204, 204));
        NovoEfetivo_departamento_in.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NovoEfetivo_departamento_inKeyPressed(evt);
            }
        });

        NovoEfetivo_nivel_in.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "D1", "D2", "D3" }));

        NovoEfetivo_titulacao_in.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Graduação", "Mestrado", "Doutorado", "Livre-Docente", "Titular" }));

        NovoEfetivo_Criar.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        NovoEfetivo_Criar.setText("Criar");
        NovoEfetivo_Criar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NovoEfetivo_CriarMouseClicked(evt);
            }
        });

        NovoEfetivo_area_in.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Biológicas", "Exatas", "Humanas", "Saúde" }));

        NovoEfetivo_Inserir_departamento.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        NovoEfetivo_Inserir_departamento.setText("Inserir o departamento do Efetivo:");

        NovoEfetivo_Aviso.setFont(new java.awt.Font("Yu Gothic", 0, 10)); // NOI18N
        NovoEfetivo_Aviso.setForeground(new java.awt.Color(102, 102, 102));
        NovoEfetivo_Aviso.setText("obs: O funcionário somente será criado se o departamento for válido (existir).");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NovoEfetivo_Titulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NovoEfetivo_Aviso))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NovoEfetivo_Descricao)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(NovoEfetivo_Inserir_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(NovoEfetivo_codigo_in, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(NovoEfetivo_Inserir_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(NovoEfetivo_nome_in, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(NovoEfetivo_Inserir_area)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(NovoEfetivo_Inserir_salario, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(NovoEfetivo_salario_in, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(NovoEfetivo_Inserir_nivel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(NovoEfetivo_nivel_in, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(NovoEfetivo_Inserir_titulacao)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NovoEfetivo_area_in, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NovoEfetivo_titulacao_in, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NovoEfetivo_Inserir_departamento)
                        .addGap(25, 25, 25)
                        .addComponent(NovoEfetivo_departamento_in, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(NovoEfetivo_Criar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NovoEfetivo_Titulo)
                    .addComponent(NovoEfetivo_Aviso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NovoEfetivo_Descricao)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NovoEfetivo_Inserir_codigo)
                    .addComponent(NovoEfetivo_codigo_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NovoEfetivo_Inserir_nome)
                    .addComponent(NovoEfetivo_nome_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NovoEfetivo_Inserir_salario)
                    .addComponent(NovoEfetivo_salario_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NovoEfetivo_Inserir_nivel)
                    .addComponent(NovoEfetivo_nivel_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NovoEfetivo_Inserir_titulacao)
                    .addComponent(NovoEfetivo_titulacao_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NovoEfetivo_Inserir_area)
                    .addComponent(NovoEfetivo_area_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NovoEfetivo_Inserir_departamento)
                    .addComponent(NovoEfetivo_departamento_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NovoEfetivo_Criar))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NovoEfetivo_CriarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NovoEfetivo_CriarMouseClicked
        if (NovoEfetivo_Criar.isEnabled()) {
            String codigo = NovoEfetivo_codigo_in.getText();
            String nome = NovoEfetivo_nome_in.getText();
            float salario = Float.parseFloat(NovoEfetivo_salario_in.getText());
            String nivel = (String) NovoEfetivo_nivel_in.getSelectedItem();
            String titulacao = (String) NovoEfetivo_titulacao_in.getSelectedItem();
            String area = (String) NovoEfetivo_area_in.getSelectedItem();
            String departamento = NovoEfetivo_departamento_in.getText();
            Sistema s19 = Sistema.getInstance();
            int aux1 = 0;
            String aux2;
            while (aux1 < s19.maxFunc) {
                aux2 = s19.funcionarios[aux1].getCodigo();
                if (aux2.equals(codigo)) {
                    new Mensagem05(null, true).setVisible(true);
                    dispose();
                    return;
                }
                aux1++;
            }
            aux1 = 0;
            while (aux1 < s19.maxDepart) {
                aux2 = s19.departamentos[aux1].getNome();
                if(aux2.equals(departamento)) {
                    Controlador control = new Controlador();
                    control.inserirFuncionario("Docente Efetivo", codigo, nome, nivel, titulacao, area, salario, 0, aux1);
                    new Mensagem13(null, true).setVisible(true);
                    dispose();
                    return;
                }
                aux1++;
            }
            new Mensagem15(null, true).setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_NovoEfetivo_CriarMouseClicked

    private void NovoEfetivo_codigo_inKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NovoEfetivo_codigo_inKeyPressed
        if (!"".equals(NovoEfetivo_codigo_in.getText())) {
            if (!"".equals(NovoEfetivo_nome_in.getText())) {
                if (!"".equals(NovoEfetivo_salario_in.getText())) {
                    if (!"".equals(NovoEfetivo_departamento_in.getText())) {
                        NovoEfetivo_Criar.setEnabled(true);
                    }
                }
            }
        }
    }//GEN-LAST:event_NovoEfetivo_codigo_inKeyPressed

    private void NovoEfetivo_nome_inKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NovoEfetivo_nome_inKeyPressed
        if (!"".equals(NovoEfetivo_codigo_in.getText())) {
            if (!"".equals(NovoEfetivo_nome_in.getText())) {
                if (!"".equals(NovoEfetivo_salario_in.getText())) {
                    if (!"".equals(NovoEfetivo_departamento_in.getText())) {
                        NovoEfetivo_Criar.setEnabled(true);
                    }
                }
            }
        }
    }//GEN-LAST:event_NovoEfetivo_nome_inKeyPressed

    private void NovoEfetivo_salario_inKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NovoEfetivo_salario_inKeyPressed
        if (!"".equals(NovoEfetivo_codigo_in.getText())) {
            if (!"".equals(NovoEfetivo_nome_in.getText())) {
                if (!"".equals(NovoEfetivo_salario_in.getText())) {
                    if (!"".equals(NovoEfetivo_departamento_in.getText())) {
                        NovoEfetivo_Criar.setEnabled(true);
                    }
                }
            }
        }
    }//GEN-LAST:event_NovoEfetivo_salario_inKeyPressed

    private void NovoEfetivo_departamento_inKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NovoEfetivo_departamento_inKeyPressed
        if (!"".equals(NovoEfetivo_codigo_in.getText())) {
            if (!"".equals(NovoEfetivo_nome_in.getText())) {
                if (!"".equals(NovoEfetivo_salario_in.getText())) {
                    if (!"".equals(NovoEfetivo_departamento_in.getText())) {
                        NovoEfetivo_Criar.setEnabled(true);
                    }
                }
            }
        }
    }//GEN-LAST:event_NovoEfetivo_departamento_inKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovoEfetivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovoEfetivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovoEfetivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovoEfetivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NovoEfetivo dialog = new NovoEfetivo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NovoEfetivo_Aviso;
    private javax.swing.JButton NovoEfetivo_Criar;
    private javax.swing.JLabel NovoEfetivo_Descricao;
    private javax.swing.JLabel NovoEfetivo_Inserir_area;
    private javax.swing.JLabel NovoEfetivo_Inserir_codigo;
    private javax.swing.JLabel NovoEfetivo_Inserir_departamento;
    private javax.swing.JLabel NovoEfetivo_Inserir_nivel;
    private javax.swing.JLabel NovoEfetivo_Inserir_nome;
    private javax.swing.JLabel NovoEfetivo_Inserir_salario;
    private javax.swing.JLabel NovoEfetivo_Inserir_titulacao;
    private javax.swing.JLabel NovoEfetivo_Titulo;
    private javax.swing.JComboBox<String> NovoEfetivo_area_in;
    private javax.swing.JTextField NovoEfetivo_codigo_in;
    private javax.swing.JTextField NovoEfetivo_departamento_in;
    private javax.swing.JComboBox<String> NovoEfetivo_nivel_in;
    private javax.swing.JTextField NovoEfetivo_nome_in;
    private javax.swing.JTextField NovoEfetivo_salario_in;
    private javax.swing.JComboBox<String> NovoEfetivo_titulacao_in;
    // End of variables declaration//GEN-END:variables
}
