/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import universidade.Sistema;
import universidade.Controlador;

/**
 *
 * @author Pedro Henrique Zago Costa - R.A.: 181257084
 * 
 * NovoTecnico.java -> Este JDialog é responsável pelas entradas de dados
 * que representam as informações de um novo Técnico a ser cadastrado.
 */
public class NovoTecnico extends javax.swing.JDialog {

    /**
     * Creates new form NovoTecnico
     */
    public NovoTecnico(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        NovoTecnico_Criar.setEnabled(false);
        setTitle("Novo Técnico");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NovoTecnico_Titulo = new javax.swing.JLabel();
        NovoTecnico_Descricao = new javax.swing.JLabel();
        NovoTecnico_Inserir_codigo = new javax.swing.JLabel();
        NovoTecnico_Inserir_nome = new javax.swing.JLabel();
        NovoTecnico_Inserir_salario = new javax.swing.JLabel();
        NovoTecnico_Inserir_nivel = new javax.swing.JLabel();
        NovoTecnico_Inserir_funcao = new javax.swing.JLabel();
        NovoTecnico_Inserir_departamento = new javax.swing.JLabel();
        NovoTecnico_codigo_in = new javax.swing.JTextField();
        NovoTecnico_nome_in = new javax.swing.JTextField();
        NovoTecnico_salario_in = new javax.swing.JTextField();
        NovoTecnico_departamento_in = new javax.swing.JTextField();
        NovoTecnico_nivel_in = new javax.swing.JComboBox<>();
        NovoTecnico_funcao_in = new javax.swing.JComboBox<>();
        NovoTecnico_Criar = new javax.swing.JButton();
        NovoTecnico_Aviso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        NovoTecnico_Titulo.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        NovoTecnico_Titulo.setText("Novo Técnico");

        NovoTecnico_Descricao.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        NovoTecnico_Descricao.setForeground(new java.awt.Color(153, 0, 0));
        NovoTecnico_Descricao.setText("Inserir novo Técnico no Sistema:");

        NovoTecnico_Inserir_codigo.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        NovoTecnico_Inserir_codigo.setText("Inserir o código do Técnico:");

        NovoTecnico_Inserir_nome.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        NovoTecnico_Inserir_nome.setText("Inserir o nome do Técnico:");

        NovoTecnico_Inserir_salario.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        NovoTecnico_Inserir_salario.setText("Inserir o salário do Técnico:");

        NovoTecnico_Inserir_nivel.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        NovoTecnico_Inserir_nivel.setText("Inserir o nível do Técnico:");

        NovoTecnico_Inserir_funcao.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        NovoTecnico_Inserir_funcao.setText("Inserir a função do Técnico:");

        NovoTecnico_Inserir_departamento.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        NovoTecnico_Inserir_departamento.setText("Inserir o departamento do Técnico:");

        NovoTecnico_codigo_in.setBackground(new java.awt.Color(255, 204, 204));
        NovoTecnico_codigo_in.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NovoTecnico_codigo_inKeyPressed(evt);
            }
        });

        NovoTecnico_nome_in.setBackground(new java.awt.Color(255, 204, 204));
        NovoTecnico_nome_in.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NovoTecnico_nome_inKeyPressed(evt);
            }
        });

        NovoTecnico_salario_in.setBackground(new java.awt.Color(255, 204, 204));
        NovoTecnico_salario_in.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NovoTecnico_salario_inKeyPressed(evt);
            }
        });

        NovoTecnico_departamento_in.setBackground(new java.awt.Color(255, 204, 204));
        NovoTecnico_departamento_in.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NovoTecnico_departamento_inKeyPressed(evt);
            }
        });

        NovoTecnico_nivel_in.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "T1", "T2" }));

        NovoTecnico_funcao_in.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Assessor", "Laboratório", "Secretário" }));

        NovoTecnico_Criar.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        NovoTecnico_Criar.setText("Criar");
        NovoTecnico_Criar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NovoTecnico_CriarMouseClicked(evt);
            }
        });

        NovoTecnico_Aviso.setFont(new java.awt.Font("Yu Gothic", 0, 10)); // NOI18N
        NovoTecnico_Aviso.setForeground(new java.awt.Color(102, 102, 102));
        NovoTecnico_Aviso.setText("obs: O funcionário somente será criado se o departamento for válido (existir).");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NovoTecnico_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                                .addComponent(NovoTecnico_Aviso))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NovoTecnico_Descricao)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(NovoTecnico_Inserir_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NovoTecnico_codigo_in, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(NovoTecnico_Inserir_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NovoTecnico_nome_in, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(NovoTecnico_Inserir_departamento)
                                        .addGap(18, 18, 18)
                                        .addComponent(NovoTecnico_departamento_in, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(NovoTecnico_Inserir_salario, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NovoTecnico_salario_in, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NovoTecnico_Inserir_nivel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NovoTecnico_Inserir_funcao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NovoTecnico_nivel_in, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NovoTecnico_funcao_in, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NovoTecnico_Criar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(217, 217, 217))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NovoTecnico_Titulo)
                    .addComponent(NovoTecnico_Aviso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NovoTecnico_Descricao)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NovoTecnico_Inserir_codigo)
                    .addComponent(NovoTecnico_codigo_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NovoTecnico_Inserir_nome)
                    .addComponent(NovoTecnico_nome_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NovoTecnico_Inserir_salario)
                    .addComponent(NovoTecnico_salario_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NovoTecnico_Inserir_nivel)
                    .addComponent(NovoTecnico_nivel_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NovoTecnico_Inserir_funcao)
                    .addComponent(NovoTecnico_funcao_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NovoTecnico_Inserir_departamento)
                    .addComponent(NovoTecnico_departamento_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NovoTecnico_Criar)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NovoTecnico_CriarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NovoTecnico_CriarMouseClicked
        if (NovoTecnico_Criar.isEnabled()) {
            String codigo = NovoTecnico_codigo_in.getText();
            String nome = NovoTecnico_nome_in.getText();
            float salario = Float.parseFloat(NovoTecnico_salario_in.getText());
            String nivel = (String) NovoTecnico_nivel_in.getSelectedItem();
            String funcao = (String) NovoTecnico_funcao_in.getSelectedItem();
            String departamento = NovoTecnico_departamento_in.getText();
            Sistema s18 = Sistema.getInstance();
            int aux1 = 0;
            String aux2;
            while (aux1 < s18.maxFunc) {
                aux2 = s18.funcionarios[aux1].getCodigo();
                if (aux2.equals(codigo)) {
                    new Mensagem05(null, true).setVisible(true);
                    dispose();
                    return;
                }
                aux1++;
            }
            aux1 = 0;
            while (aux1 < s18.maxDepart) {
                aux2 = s18.departamentos[aux1].getNome();
                if(aux2.equals(departamento)) {
                    Controlador control = new Controlador();
                    control.inserirFuncionario("Tecnico", codigo, nome, nivel, funcao, "", salario, 0, aux1);
                    new Mensagem13(null, true).setVisible(true);
                    dispose();
                    return;
                }
                aux1++;
            }
            new Mensagem15(null, true).setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_NovoTecnico_CriarMouseClicked

    private void NovoTecnico_codigo_inKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NovoTecnico_codigo_inKeyPressed
        if (!"".equals(NovoTecnico_codigo_in.getText())) {
            if (!"".equals(NovoTecnico_nome_in.getText())) {
                if (!"".equals(NovoTecnico_salario_in.getText())) {
                    if (!"".equals(NovoTecnico_departamento_in.getText())) {
                        NovoTecnico_Criar.setEnabled(true);
                    }
                }
            }
        }
    }//GEN-LAST:event_NovoTecnico_codigo_inKeyPressed

    private void NovoTecnico_nome_inKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NovoTecnico_nome_inKeyPressed
        if (!"".equals(NovoTecnico_codigo_in.getText())) {
            if (!"".equals(NovoTecnico_nome_in.getText())) {
                if (!"".equals(NovoTecnico_salario_in.getText())) {
                    if (!"".equals(NovoTecnico_departamento_in.getText())) {
                        NovoTecnico_Criar.setEnabled(true);
                    }
                }
            }
        }
    }//GEN-LAST:event_NovoTecnico_nome_inKeyPressed

    private void NovoTecnico_salario_inKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NovoTecnico_salario_inKeyPressed
        if (!"".equals(NovoTecnico_codigo_in.getText())) {
            if (!"".equals(NovoTecnico_nome_in.getText())) {
                if (!"".equals(NovoTecnico_salario_in.getText())) {
                    if (!"".equals(NovoTecnico_departamento_in.getText())) {
                        NovoTecnico_Criar.setEnabled(true);
                    }
                }
            }
        }
    }//GEN-LAST:event_NovoTecnico_salario_inKeyPressed

    private void NovoTecnico_departamento_inKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NovoTecnico_departamento_inKeyPressed
        if (!"".equals(NovoTecnico_codigo_in.getText())) {
            if (!"".equals(NovoTecnico_nome_in.getText())) {
                if (!"".equals(NovoTecnico_salario_in.getText())) {
                    if (!"".equals(NovoTecnico_departamento_in.getText())) {
                        NovoTecnico_Criar.setEnabled(true);
                    }
                }
            }
        }
    }//GEN-LAST:event_NovoTecnico_departamento_inKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovoTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovoTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovoTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovoTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NovoTecnico dialog = new NovoTecnico(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NovoTecnico_Aviso;
    private javax.swing.JButton NovoTecnico_Criar;
    private javax.swing.JLabel NovoTecnico_Descricao;
    private javax.swing.JLabel NovoTecnico_Inserir_codigo;
    private javax.swing.JLabel NovoTecnico_Inserir_departamento;
    private javax.swing.JLabel NovoTecnico_Inserir_funcao;
    private javax.swing.JLabel NovoTecnico_Inserir_nivel;
    private javax.swing.JLabel NovoTecnico_Inserir_nome;
    private javax.swing.JLabel NovoTecnico_Inserir_salario;
    private javax.swing.JLabel NovoTecnico_Titulo;
    private javax.swing.JTextField NovoTecnico_codigo_in;
    private javax.swing.JTextField NovoTecnico_departamento_in;
    private javax.swing.JComboBox<String> NovoTecnico_funcao_in;
    private javax.swing.JComboBox<String> NovoTecnico_nivel_in;
    private javax.swing.JTextField NovoTecnico_nome_in;
    private javax.swing.JTextField NovoTecnico_salario_in;
    // End of variables declaration//GEN-END:variables
}
